### ISSUE TITLE
The system cannot find the path specified: '/mnt/games/*.*

### ISSUE THREAD

**Issue by orlyyani** [erikbern/deep-pink#19]
I'm in windows and it seems it's because of os.listdir() has different functionality in unix?

**Comment by erikbern** [comment]
ok probably have to update the path then!

**Comment by nullworth** [comment]
Im using fedora. this error comes up after entering     python parse_game.py . what should i do?

/home/null/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "parse_game.py", line 149, in <module>
    parse_dir()
  File "parse_game.py", line 136, in parse_dir
    for fn_in in os.listdir(d):
OSError: [Errno 2] No such file or directory: '/mnt/games'

**Comment by erikbern** [comment]
well do you have that directory on your computer?

**Comment by Ashbajawed** [comment]
> well do you have that directory on your computer?

hello @erikbern I downloaded data from [ficsgames website](http://www.ficsgames.org/download.html) . its in.pgn formate what I need to do now?

**Comment by erikbern** [comment]
sorry, this project is extremely old and very unsupported at this point!
