### ISSUE TITLE
AssertionError - assert(gn_current.board().turn == 0)

### ISSUE THREAD

**Issue by rayexar** [erikbern/deep-pink#6]
I'm getting AssertionErrors when trying to run play.py, with the output looking like this:

```
maxd 1.000000 maxn 278.426311
Traceback (most recent call last):
  File "C:\Users\Lol\Desktop\deep-pink-master\deep-pink-master\play.py", line 226, in game
    gn_current = player.move(gn_current)
  File "C:\Users\Lol\Desktop\deep-pink-master\deep-pink-master\play.py", line 119, in move
    assert(gn_current.board().turn == 0)
AssertionError
```

and keeps repeating itself. Any idea on how to fix this?

**Comment by erikbern** [comment]
The model can only play one of the sides (i don't remember which but I think black)

Are you running it off the shelf or did you make any modifications? I haven't touched this code in a year+ so I don't remember exactly how it works

**Comment by rayexar** [comment]
I'm running it off the shelf unmodified. Do I need to set sunfish to play as black or modify play.py?

BTW, merry christmas!

**Comment by rayexar** [comment]
I'm running it off the shelf. It looks like with sunfish the player plays as white by default (although the pieces are displayed as black for some reason).

**Comment by vyasgiridhar** [comment]
How did you solve the infinite assersion errors? @rayexar

**Comment by rayexar** [comment]
@vyasgiridhar I didn't manage to fix that...

**Comment by vyasgiridhar** [comment]
@rayexar I found the mistake
The problem is at gn_current.board().turn. It returns a boolean, not a integer.

**Comment by erikbern** [comment]
great if you want to submit a pull request and fix it

**Comment by erikbern** [comment]
just do `assert(not gn_current.board())` should be enough
